opt_in_rules:
  - empty_count
included:
  - Sources
disabled_rules:
  - function_parameter_count
  - identifier_name
  - type_body_length
  - file_length
  - empty_count
  - type_name
  - shorthand_operator

force_cast: warning
force_try:
  severity: warning
line_length: 140
function_body_length: 200

type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
reporter: "xcode"
